### ISSUE TITLE
(Marathon, Piece Trial) Best Score isn't saved

### ISSUE THREAD

**Issue by Talon125** [mstop4/bomino#1]
Best Time in Sprint is saved, but Best Score in Marathon and Piece Trial isn't.    

https://user-images.githubusercontent.com/101049742/223826311-fbc6bfeb-921d-4124-be40-bb01d980b065.mp4    

https://user-images.githubusercontent.com/101049742/223826360-a644131a-08ce-4b7a-bb50-e61c67bcd442.mp4

**Comment by mstop4** [comment]
Fixed in v0.18
