### ISSUE TITLE
Pre-DAS delay does not reset when holding both directions

### ISSUE THREAD

**Issue by Xx-Henry-xX** [mstop4/bomino#2]
(0.17.2)
Procedures for recreating this bug
1. Hold one of Left/Right and make DAS kick in
2. Keep the direction in 1 held and press the other direction
3. Pre-DAS delay is gone

This caused a few misdrops when I tried playing fast...

**Comment by mstop4** [comment]
The bug was already reported in the internal bug tracker. Fixed in v0.18.
