### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by BlandJar** [mstop4/bomino#3]
![20231130_111039](https://github.com/mstop4/bomino/assets/102204373/9e3f95fa-cf82-453d-9134-a2120d0ab06a)
I'm playing the Linux version on a Steam Deck. I'm not sure if it helps but I was playing Marathon mode, goal 2000 minos, piece set easy, starting level 15

**Comment by mstop4** [comment]
Hi,

I'll look into it.

**Comment by mstop4** [comment]
I managed to reproduce the issue:

https://github.com/mstop4/bomino/assets/15877646/28a6e6b9-b462-469f-8814-dcfe43b93c0c

**Step to reproduce:**
1. Make two difficult line fills (e.g. quads or better, Spin fills) to get Back-to-Back status.
2. Perform a Spin without line fills, the crash occurs. 

This should be a simple fix.

**Comment by mstop4** [comment]
Crash is now fixed in v0.21.1
https://quadolorgames.itch.io/bomino/devlog/645078/bomino-v0211-hotfix
