### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BlandJar** [mstop4/bomino#4]
I failed to take a video of it cuz I swear I pressed the record button on my phone :( 
![20231129_205733](https://github.com/mstop4/bomino/assets/102204373/b981222c-5aab-4e40-90d3-915b2e3ea28d)
but I found a glitch where the blocks turn invisible and sometimes the image of the blocks is in the wrong spot.

This image is the only thing I have.

**Comment by mstop4** [comment]
I think I've seen this bug as well while working on the game, but I had a hard time trying to reproduce it. I'll keep an eye for it.

**Comment by mstop4** [comment]
Someone else has reported this bug on the itch.io forum: https://itch.io/post/9221487
The bug also occurring in Dig mode.

**Comment by mstop4** [comment]
Just tried playing Dig mode for almost 30 minutes and the bug doesn't seem to happen anymore 🤔. The problem might have fixed itself over time; maybe a very obscure issue with an older version of the GameMaker runtime was causing the bug.
